import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Provider } from "react-redux";
import { cn, poppins } from "@/lib/utils";
import Navbar from "@/components/shared/navbar/Navbar";
import Footer from "@/components/shared/Footer";

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by LMS app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "text-[#1f2732]")}>
        <Navbar /> <div className="pt-[57px]">{children}</div> <Footer />
        <Toaster />
      </body>
    </html>
  );
}
