import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { Provider } from "react-redux";
import { cn, poppins } from "@/lib/utils";

export const metadata: Metadata = {
  title: "LMS App",
  description: "Generated by LMS app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "text-[#1f2732]")}>
        <Toaster /> {children}
      </body>
    </html>
  );
}
